#!/usr/bin/env php
<?php

use Bundle\Foundation\Application;

require_once __DIR__ . '/vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();


$config = [
    'DB' => [
        'DB_DRIVER'=> $_ENV['DB_DRIVER'],
        'DB_HOST'=> $_ENV['DB_HOST'],
        'DB_PORT'=> $_ENV['DB_PORT'],
        'DB_DATABASE'=> $_ENV['DB_DATABASE'],
        'DB_USERNAME'=> $_ENV['DB_USERNAME'],
        'DB_PASSWORD'=> $_ENV['DB_PASSWORD'],
    ]
];


$app = new Application(__DIR__, $config);
$app->connection->apply();